### ISSUE TITLE
Which exact version of unity are we using?

### ISSUE THREAD

**Issue by Sean-Ye-Student** [EfeTascioglu/YMDesignTeam#2]

**Comment by EfeTascioglu** [comment]
We will most likely be using 2019.4.15f1 (LTS), as that is a LTS that everyone can get, and the one that was recommended when I first sent the Unity download link. It does not make a different if you open the project with 2019.4.16f1 (LTS), but please get 2019.4.15f1 (LTS), to not change version files.

**Comment by Sean-Ye-Student** [comment]
Thanks
